/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import java.text.SimpleDateFormat;
import control.DAO;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;
import model.*;
import model.SystemSemester;
import model.StudentSemester;
import model.CourseResult;
import model.Student;

/**
 *
 * @author Admin
 */
public class AddStudentView extends javax.swing.JFrame {
    private University university;
    /**
     * Creates new form AddStudentForm
     */
    public AddStudentView(University university) {
        this.university = university;
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtontc);
        bg.add(jRadioButtonnc);
        jRadioButtontc.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_hoten = new javax.swing.JLabel();
        jLabel_hesinhvien = new javax.swing.JLabel();
        jLabel_trangthaihoctap = new javax.swing.JLabel();
        jTextField_hoten = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jRadioButtontc = new javax.swing.JRadioButton();
        jRadioButtonnc = new javax.swing.JRadioButton();
        jButton_cancel = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jLabel_mssv = new javax.swing.JLabel();
        jTextField_manganhhoc = new javax.swing.JTextField();
        jLabel_manghanhhoc = new javax.swing.JLabel();
        jTextField_mssv = new javax.swing.JTextField();
        jLabel_machuongtrinh = new javax.swing.JLabel();
        jTextField_machuongtrinhhoc = new javax.swing.JTextField();
        jLabel_malop = new javax.swing.JLabel();
        jTextField_trangthaihoctap = new javax.swing.JTextField();
        jTextField_malop = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New Student");

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_username.setText("Username:");

        jLabel_hoten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_hoten.setText("Ho va Ten:");

        jLabel_hesinhvien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_hesinhvien.setText("He Sinh Vien:");

        jLabel_trangthaihoctap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_trangthaihoctap.setText("Trang thai  ht:");

        jTextField_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hotenActionPerformed(evt);
            }
        });

        jRadioButtontc.setText("TC");

        jRadioButtonnc.setText("NC");
        jRadioButtonnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonncActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jLabel_mssv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_mssv.setText("MSSV:");

        jTextField_manganhhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_manganhhocActionPerformed(evt);
            }
        });

        jLabel_manghanhhoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_manghanhhoc.setText("Ma nganh:");

        jLabel_machuongtrinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_machuongtrinh.setText("Ma chuong trinh:");

        jLabel_malop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_malop.setText("Ma lop:");

        jTextField_trangthaihoctap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_trangthaihoctapActionPerformed(evt);
            }
        });

        jTextField_malop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_malopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_machuongtrinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_machuongtrinhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_cancel)
                                .addGap(194, 194, 194)
                                .addComponent(jButton_add))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_username)
                                            .addComponent(jLabel_hesinhvien)
                                            .addComponent(jLabel_manghanhhoc)
                                            .addComponent(jLabel_mssv))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel_hoten)
                                            .addGap(18, 18, 18)))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_manganhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonnc)
                                        .addGap(90, 90, 90)
                                        .addComponent(jRadioButtontc))
                                    .addComponent(jTextField_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_malop)
                                    .addComponent(jLabel_trangthaihoctap))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_malop, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_trangthaihoctap, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_hoten)
                    .addComponent(jTextField_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_username, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_mssv, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_mssv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_hesinhvien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonnc)
                        .addComponent(jRadioButtontc)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_manghanhhoc)
                    .addComponent(jTextField_manganhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_machuongtrinh)
                    .addComponent(jTextField_machuongtrinhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_malop)
                    .addComponent(jTextField_malop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_trangthaihoctap)
                    .addComponent(jTextField_trangthaihoctap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_cancel))
                .addContainerGap())
        );

        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hotenActionPerformed

    private void jRadioButtonncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonncActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed
    public boolean verifText(){
        if(jTextField_hoten.getText().equals("") ||jTextField_username.getText().equals("") || jTextField_mssv.getText().equals("")
                ||jTextField_manganhhoc.getText().equals("")||jTextField_machuongtrinhhoc.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"One or more empty field");  
            return false;
        }
     
        else
            return true;
        
    }
    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
		  		  DAO dao = new DAO(university);

        String fullName = jTextField_hoten.getText();
        String username = jTextField_username.getText();
        String mssv = jTextField_mssv.getText();
        String schoolID = jTextField_manganhhoc.getText();
        String programID = jTextField_machuongtrinhhoc.getText();
        String studentClassID = jTextField_malop.getText();
        String trangThaiHocTap = jTextField_trangthaihoctap.getText();
       // String hocki = jTextField_hocki.getText();
        String heSinhVien = "TC";
        if(jRadioButtonnc.isSelected())
            heSinhVien = "NC";
        
        //SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       // String bdate = dateFormat.format(dateChooserCombo.getSelectedDate());
        
       if(verifText()){
      
           
            if(dao.insertDeleteUpdateStudent('i', null, heSinhVien, mssv, fullName, username, username, schoolID, programID, studentClassID,trangThaiHocTap,null))
            {
               // AdminView.jTable1.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien","mssv","fullName","username","maNganh","maChuongTrinh","maLop","trangThai","hocki"}));
                
                dao.fillStudentJtable(AdminView.jTableSinhVien, "");
               // university hethong = new university();
                ArrayList<SystemSemester> hockyhethong = new ArrayList<SystemSemester>();
//                ArrayList<StudentSemester> studentSemesterList = 
//                ArrayList<CourseResult> listBangDiem = ;
                hockyhethong = university.getSystemSemesterList();
                StudentSemester a = new StudentSemester(mssv,hockyhethong.get(hockyhethong.size()-1).getSystemSemesterID(),new ArrayList<>(),new ArrayList<>());         
                a.setMaHocKyHeThong(hockyhethong.get(hockyhethong.size()-1).getSystemSemesterID());
		a.setMssv(mssv);
//                studentSemesterList.add(a);

                Student sv = new Student(mssv,fullName,username,username,trangThaiHocTap,null,studentClassID,programID,schoolID,new ArrayList<>(),new ArrayList<>());
                sv.getHocKySinhVien().add(a);
               
                university.findStudentClass(studentClassID).getSinhVien().add(sv);
                university.getStudentList().add(sv);
                dao.insertHocKySinhVien(mssv, hockyhethong.get(hockyhethong.size()-1).getSystemSemesterID());
                dao.updateSiSoLopSinhVien('i',studentClassID,university.findStudentClass(studentClassID).getSinhVien().size());
                                
            }
            //dao.fillStudentJtable(AdminView.jTable1, "");
       }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTextField_trangthaihoctapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_trangthaihoctapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_trangthaihoctapActionPerformed

    private void jTextField_manganhhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_manganhhocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_manganhhocActionPerformed

    private void jTextField_malopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_malopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_malopActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddStudentView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_hesinhvien;
    private javax.swing.JLabel jLabel_hoten;
    private javax.swing.JLabel jLabel_machuongtrinh;
    private javax.swing.JLabel jLabel_malop;
    private javax.swing.JLabel jLabel_manghanhhoc;
    private javax.swing.JLabel jLabel_mssv;
    private javax.swing.JLabel jLabel_trangthaihoctap;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonnc;
    private javax.swing.JRadioButton jRadioButtontc;
    private javax.swing.JTextField jTextField_hoten;
    private javax.swing.JTextField jTextField_machuongtrinhhoc;
    private javax.swing.JTextField jTextField_malop;
    private javax.swing.JTextField jTextField_manganhhoc;
    private javax.swing.JTextField jTextField_mssv;
    private javax.swing.JTextField jTextField_trangthaihoctap;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
