package view;

import control.DAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 * @author hai DESCIPTION:
 */
public class AdminView extends javax.swing.JFrame {

    /*======================= ATTRIBUTEs ==============================*/
    private University university;
    private String adminID;
//	 private Admin admin;//thay = adminID

    DefaultTableModel courseRegistrationModel;
    DefaultTableModel courseClassRegistrationModel;
    DefaultTableModel openingClassesModel;

    //duc
    DefaultTableModel modelSinhVien;

    /*======================= CONSTRUCTORs ==============================*/
    /**
     * Creates new form AdminView
     *
     * @param university
     * @param adminID
     */
    public AdminView(University university, String adminID) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        initComponents();
        this.setLocationRelativeTo(null);

        this.university = university;
        this.adminID = adminID;

        jLabelAdminID.setText("Admin ID: " + adminID);
        jLabelToday.setText("Today: " + String.valueOf(university.getToday()));
        jLabelSystemSemester.setText("Semester: " + university.getSystemSemesterList().get(university.getSystemSemesterList().size() - 1).getSystemSemesterID());

        courseRegistrationModel = (DefaultTableModel) jTableCourseRegistration.getModel();
        courseClassRegistrationModel = (DefaultTableModel) jTableCourseClassRegistration.getModel();
        openingClassesModel = (DefaultTableModel) jTableOpeningCourseClasses.getModel();

        //duc
        modelSinhVien = (DefaultTableModel) jTableSinhVien.getModel();

        this.getSystemSemesterID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel_hovaten = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_mssv = new javax.swing.JLabel();
        jLabel_hesinhvien = new javax.swing.JLabel();
        jLabel_machuongtrinh = new javax.swing.JLabel();
        jLabel_malop = new javax.swing.JLabel();
        jLabel_trangthaihoctap = new javax.swing.JLabel();
        jTextField_hovaten = new javax.swing.JTextField();
        jTextField_mssv = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jRadioButtonnc = new javax.swing.JRadioButton();
        jRadioButtontc = new javax.swing.JRadioButton();
        jTextField_manganhhoc = new javax.swing.JTextField();
        jLabel_manghanhhoc = new javax.swing.JLabel();
        jTextField_machuongtrinhhoc = new javax.swing.JTextField();
        jTextField_malop = new javax.swing.JTextField();
        jTextField_trangthaihoctap = new javax.swing.JTextField();
        jLabel_find = new javax.swing.JLabel();
        jTextField_find = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSinhVien = new javax.swing.JTable();
        jButton_add = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCourseRegistration = new javax.swing.JTable();
        jComboBoxSystemSemesterID1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStudentID1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCourseID = new javax.swing.JTextField();
        jButtonRegisterCourse = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCourseClassRegistration = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSystemSemesterID2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldStudentID2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCourseClassID = new javax.swing.JTextField();
        jButtonRegisterCourseClass = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableOpeningCourseClasses = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCourseID2 = new javax.swing.JTextField();
        jButtonSeeOpeningCourseClasses = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxSystemSemeserID3 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelAdminID = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabelToday = new javax.swing.JLabel();
        jLabelSystemSemester = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Session");
        setAutoRequestFocus(false);

        jTabbedPane3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_hovaten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_hovaten.setText("Full name");

        jLabel_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_username.setText("Username");

        jLabel_mssv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_mssv.setText("Student ID");

        jLabel_hesinhvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_hesinhvien.setText("Student type");

        jLabel_machuongtrinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_machuongtrinh.setText("Program ID");

        jLabel_malop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_malop.setText("Student class ID");

        jLabel_trangthaihoctap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_trangthaihoctap.setText("Status");

        jTextField_hovaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hovatenActionPerformed(evt);
            }
        });

        jTextField_mssv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mssvActionPerformed(evt);
            }
        });

        jRadioButtonnc.setText("Yearly");
        jRadioButtonnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonncActionPerformed(evt);
            }
        });

        jRadioButtontc.setText("Unit");

        jTextField_manganhhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_manganhhocActionPerformed(evt);
            }
        });

        jLabel_manghanhhoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_manghanhhoc.setText("School ID");

        jTextField_malop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_malopActionPerformed(evt);
            }
        });

        jTextField_trangthaihoctap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_trangthaihoctapActionPerformed(evt);
            }
        });

        jLabel_find.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_find.setText("Enter student ID for searching");

        jTextField_find.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_findActionPerformed(evt);
            }
        });
        jTextField_find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_findKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_findKeyReleased(evt);
            }
        });

        jTableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Student ID", "Full name", "School ID", "Program ID", "Student class ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSinhVienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableSinhVien);

        jButton_add.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-student-registration-25.png")); // NOI18N
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_edit.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-pencil-25.png")); // NOI18N
        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_remove.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-trash-25.png")); // NOI18N
        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_hovaten)
                    .addComponent(jLabel_username)
                    .addComponent(jLabel_hesinhvien)
                    .addComponent(jLabel_manghanhhoc)
                    .addComponent(jLabel_trangthaihoctap)
                    .addComponent(jLabel_malop)
                    .addComponent(jLabel_machuongtrinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_hovaten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_mssv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_manganhhoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_machuongtrinhhoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_malop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_trangthaihoctap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_remove)
                .addGap(30, 30, 30)
                .addComponent(jButton_edit)
                .addGap(46, 46, 46)
                .addComponent(jButton_add)
                .addGap(670, 670, 670))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel_find)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField_find, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jRadioButtonnc)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtontc))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel_mssv)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_find)
                    .addComponent(jTextField_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_hovaten)
                            .addComponent(jTextField_hovaten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_username)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_mssv)
                            .addComponent(jTextField_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_hesinhvien)
                            .addComponent(jRadioButtonnc)
                            .addComponent(jRadioButtontc))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_manghanhhoc)
                            .addComponent(jTextField_manganhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_machuongtrinhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_machuongtrinh))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_malop)
                            .addComponent(jTextField_malop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_trangthaihoctap)
                            .addComponent(jTextField_trangthaihoctap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_add)
                            .addComponent(jButton_edit)
                            .addComponent(jButton_remove))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );


        jTabbedPane3.addTab("Student list", jPanel7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Graduation", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Manage student", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "School ID", "School name", "Program number", "Student class number", "Student number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable1);

        jButton1.setText("Search school");

        jButton2.setText("Edit school");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(jButton2)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane4.addTab("School", jPanel10);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Program ID", "Program name", "Student class number", "Student number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable2);

        jButton3.setText("Search program");

        jButton4.setText("Edit program");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addComponent(jScrollPane7)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)))
        );

        jTabbedPane4.addTab("Program", jPanel11);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student class ID", "Start year", "Student number", "Program name", "School name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable3);

        jButton5.setText("Search student class");

        jButton6.setText("Edit student class");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton6)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)))
        );

        jTabbedPane4.addTab("Student class", jPanel12);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course name", "Condition courses", "Mid term", "End term", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTable4);

        jButton7.setText("Search course");

        jButton8.setText("Edit course");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane4.addTab("Course", jPanel13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane1.addTab("Manage education", jPanel2);

        jTableCourseRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course name"
            }
        ));
        jScrollPane2.setViewportView(jTableCourseRegistration);

        jLabel1.setText("Semester");

        jLabel2.setText("Student ID");

        jLabel3.setText("Course ID");

        jButtonRegisterCourse.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-study-25.png")); // NOI18N
        jButtonRegisterCourse.setText("Register course");
        jButtonRegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jComboBoxSystemSemesterID1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldStudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegisterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSystemSemesterID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonRegisterCourse)))
        );

        jTabbedPane2.addTab("Register course", jPanel4);

        jTableCourseClassRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course class ID", "Course ID", "Course name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableCourseClassRegistration);

        jLabel4.setText("Semester");

        jLabel5.setText("Student ID");

        jLabel6.setText("Class ID");

        jButtonRegisterCourseClass.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-study-25.png")); // NOI18N
        jButtonRegisterCourseClass.setText("Register class");
        jButtonRegisterCourseClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCourseClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jComboBoxSystemSemesterID2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldStudentID2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCourseClassID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonRegisterCourseClass, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonRegisterCourseClass)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSystemSemesterID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStudentID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCourseClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jTabbedPane2.addTab("Register class", jPanel5);

        jTableOpeningCourseClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course class ID", "Course ID", "Course name", "Capacity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableOpeningCourseClasses);

        jLabel11.setText("Course ID");

        jTextFieldCourseID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourseID2ActionPerformed(evt);
            }
        });

        jButtonSeeOpeningCourseClasses.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-view-details-25.png")); // NOI18N
        jButtonSeeOpeningCourseClasses.setText("See opening classes");
        jButtonSeeOpeningCourseClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeOpeningCourseClassesActionPerformed(evt);
            }
        });

        jLabel8.setText("Semester");

        jComboBoxSystemSemeserID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSystemSemeserID3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxSystemSemeserID3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCourseID2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButtonSeeOpeningCourseClasses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonSeeOpeningCourseClasses)
                    .addComponent(jTextFieldCourseID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxSystemSemeserID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        jTabbedPane2.addTab("Opening course classes", jPanel14);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Graduation", jPanel9);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Input course result", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Manage study", jPanel3);

        jLabelAdminID.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelAdminID.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-male-user-25.png")); // NOI18N
        jLabelAdminID.setText("adminID");

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelToday.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-clock-25.png")); // NOI18N
        jLabelToday.setText("today");

        jLabelSystemSemester.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-calendar-25.png")); // NOI18N
        jLabelSystemSemester.setText("systemSemester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelSystemSemester)
                .addGap(85, 85, 85)
                .addComponent(jLabelToday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogout)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdminID)
                    .addComponent(jButtonLogout)
                    .addComponent(jLabelToday)
                    .addComponent(jLabelSystemSemester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*============================= OTHER ==========================================*/

    public void getSystemSemesterID() {
        jComboBoxSystemSemesterID1.removeAllItems();
        jComboBoxSystemSemesterID2.removeAllItems();
        jComboBoxSystemSemeserID3.removeAllItems();
        //add hoc ky he thong hien tai
        //admin chi dang ky hoc tap cho hoc ky hien tai
        jComboBoxSystemSemesterID1.addItem(university.getSystemSemesterList().get(university.getSystemSemesterList().size() - 1).getSystemSemesterID());
        jComboBoxSystemSemesterID2.addItem(university.getSystemSemesterList().get(university.getSystemSemesterList().size() - 1).getSystemSemesterID());
        jComboBoxSystemSemeserID3.addItem(university.getSystemSemesterList().get(university.getSystemSemesterList().size() - 1).getSystemSemesterID());
    }

    public void displayCourseRegistration() {
        courseRegistrationModel.setRowCount(0);//set model ve 0

        Course h;
        //duyet listMaHocPhanDangKy de hien thi tung hoc phan

        for (String maHocPhan : university.findStudentSemester(jTextFieldStudentID1.getText(), jComboBoxSystemSemesterID1.getSelectedItem().toString()).getMaHocPhanDangKy()) {
            h = university.findCourse(maHocPhan);//tim ra hoc phan tuong ung ma s
            courseRegistrationModel.addRow(new Object[]{
                h.getMaHocPhan(), h.getTenHocPhan()
            });
        }
    }

    public void displayCourseClassRegistration() {//hien thi cac hoc phan ma 1 sinh vien dang ky // trong 1 ky he thong

        courseClassRegistrationModel.setRowCount(0);//set model ve 0

        CourseClass h;
        //duyet listMaHocPhanDangKy de hien thi tung hoc phan

        for (String maLopMo : university.findStudentSemester(jTextFieldStudentID2.getText(), jComboBoxSystemSemesterID2.getSelectedItem().toString()).getMaLopMoDangKy()) {
            h = university.findCourseClass(maLopMo);
            courseClassRegistrationModel.addRow(new Object[]{
                h.getMaLopMo(), h.getMaHocPhan(), university.findCourse(h.getMaHocPhan()).getTenHocPhan()
            });
        }
    }

    public void displayOpeningCourseClassesBySemester() {

        openingClassesModel.setRowCount(0);//set model ve 0
        SystemSemester hkht = university.findSystemSemester(jComboBoxSystemSemeserID3.getSelectedItem().toString());

        for (CourseClass lopMo : hkht.getLopMo()) {
            if (university.findCourse(lopMo.getMaHocPhan()) instanceof UnitCourse) {//chi show nhung lopMo cua he TC

                if ((university.getToday().after(hkht.getBatDauDangKyLopMo()) && university.getToday().before(hkht.getBatDauHocKy()))) {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Opening for registering"
                    });
                } else {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Closed"
                    });

                }
            }
        }
    }

    public void displayOpeningCourseClassesBySemesterAndCourse() {

        openingClassesModel.setRowCount(0);//set model ve 0
        SystemSemester hkht = university.findSystemSemester(jComboBoxSystemSemeserID3.getSelectedItem().toString());

        for (CourseClass lopMo : hkht.getLopMo()) {
            if (lopMo.getMaHocPhan().equals(jTextFieldCourseID2.getText())) {//nếu là lớp mở của học phần đang chọn
                if ((university.getToday().after(hkht.getBatDauDangKyLopMo()) && university.getToday().before(hkht.getBatDauHocKy()))) {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Opening for registering"
                    });
                } else {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Closed"
                    });

                }
            }
        }
    }

    //duc
    public void displaySinhVien() {

        university.getStudentList().forEach((s) -> {
            if (s instanceof UnitStudent) {
                modelSinhVien.addRow(new Object[]{
                    "TC", s.getMssv(), s.getHoTen(), s.getUsername(), s.getMaNganhHoc(), s.getMaChuongTrinhHoc(), s.getMaLopSinhVien(), s.getTrangThai(), s.getBangTotNghiep()

                });
            } else {
                modelSinhVien.addRow(new Object[]{
                    "NC", s.getMssv(), s.getHoTen(), s.getUsername(), s.getMaNganhHoc(), s.getMaChuongTrinhHoc(), s.getMaLopSinhVien(), s.getTrangThai(), s.getBangTotNghiep()

                });

            }
        });
    }

    public boolean verifText() {
        if (jTextField_hovaten.getText().equals("") || jTextField_username.getText().equals("") || jTextField_mssv.getText().equals("")
                || jTextField_manganhhoc.getText().equals("") || jTextField_machuongtrinhhoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "One or more empty field");
            return false;
        } else {
            return true;
        }

    }

    /*==================================================================*/
    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO(university);
        university.initLoginSession(dao);
        this.dispose();

    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonRegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCourseActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO(university);

        if (jTextFieldStudentID1.getText().equals("") || jTextFieldCourseID.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please input Student ID and Course ID!");
        } else {
            if (university.findStudent(jTextFieldStudentID1.getText()) == null || !(university.findStudent(jTextFieldStudentID1.getText()) instanceof UnitStudent)) {
                JOptionPane.showMessageDialog(rootPane, "Wrong student ID!");
            } else {
                if (university.registerCourseForUnitStudent(jTextFieldStudentID1.getText(), jTextFieldCourseID.getText(), jComboBoxSystemSemesterID1.getSelectedItem().toString(), dao)) {
                    displayCourseRegistration();
                }
            }

        }
    }//GEN-LAST:event_jButtonRegisterCourseActionPerformed

    private void jTextField_hovatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hovatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hovatenActionPerformed

    private void jTextField_mssvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mssvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mssvActionPerformed

    private void jRadioButtonncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonncActionPerformed

    private void jTextField_manganhhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_manganhhocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_manganhhocActionPerformed

    private void jTextField_malopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_malopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_malopActionPerformed

    private void jTextField_trangthaihoctapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_trangthaihoctapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_trangthaihoctapActionPerformed

    private void jTextField_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_findActionPerformed

    private void jTextField_findKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_findKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_findKeyPressed

    private void jTextField_findKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_findKeyReleased
        // TODO add your handling code here:
        DAO dao = new DAO(university);

        jTableSinhVien.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien", "mssv", "fullName", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "bangTN"}));
        dao.fillStudentJtable(jTableSinhVien, jTextField_find.getText());
    }//GEN-LAST:event_jTextField_findKeyReleased

    private void jTableSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSinhVienMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTableSinhVien.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTableSinhVien.getModel();

        if (model.getValueAt(rowIndex, 0).equals("TC")) {
            jRadioButtontc.setSelected(true);
            jRadioButtonnc.setSelected(false);

        } else {
            jRadioButtonnc.setSelected(true);
            jRadioButtontc.setSelected(false);
        }
        jTextField_mssv.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_username.setText(model.getValueAt(rowIndex, 3).toString());
        jTextField_hovaten.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_manganhhoc.setText(model.getValueAt(rowIndex, 4).toString());
        jTextField_machuongtrinhhoc.setText(model.getValueAt(rowIndex, 5).toString());
        jTextField_malop.setText(model.getValueAt(rowIndex, 6).toString());
        //jTextField_.setText(model.getValueAt(rowIndex,8).toString());
        jTextField_trangthaihoctap.setText(model.getValueAt(rowIndex, 7).toString());
        //   jTextField_bangtotnghiep.setText(model.getValueAt(rowIndex,8).toString());
    }//GEN-LAST:event_jTableSinhVienMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // //
        this.setVisible(true);
        AddStudentView addstd = new AddStudentView(university);
        addstd.setVisible(true);
        //manageStudent mngstd = new manageStudent();
        //mngstd.setVisible(true);
        addstd.pack();
        addstd.setLocationRelativeTo(null);
        addstd.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //this.displaySinhVien();

    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO(university);

        String fullName = jTextField_hovaten.getText();
        String username = jTextField_username.getText();
        String mssv = jTextField_mssv.getText();
        String schoolID = jTextField_manganhhoc.getText();
        String programID = jTextField_machuongtrinhhoc.getText();
        String studentClassID = jTextField_malop.getText();
        String trangThaiHocTap = jTextField_trangthaihoctap.getText();
        //String bangTotNghiep = jTextField_bangtotnghiep.getText();
        String heSinhVien = "TC";
        if (jRadioButtonnc.isSelected()) {
            heSinhVien = "NC";
        }

        //SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        // String bdate = dateFormat.format(dateChooserCombo.getSelectedDate());
        if (verifText()) {
            dao.insertDeleteUpdateStudent('u', null, heSinhVien, mssv, fullName, username, username, schoolID, programID, studentClassID, trangThaiHocTap, null);
            //update object
            for (int i = 0; i <= university.getStudentList().size() - 1; i++) {
                if (university.getStudentList().get(i).getMssv().equals(mssv)) {
                    university.getStudentList().get(i).setUsername(username);
                    university.getStudentList().get(i).setPassword(username);
                    university.getStudentList().get(i).setMssv(mssv);
                    university.getStudentList().get(i).setTrangThai(trangThaiHocTap);
                    university.getStudentList().get(i).setMaNganhHoc(schoolID);
                    university.getStudentList().get(i).setMaLopSinhVien(studentClassID);
                    university.getStudentList().get(i).setMaChuongTrinhHoc(programID);
                    university.getStudentList().get(i).setHoTen(fullName);
                    university.getStudentList().get(i).setMaChuongTrinhHoc(heSinhVien);
                    // university.getStudentList().get(i).setBangTotNghiep(schoolID);
                    //  university.findStudentClass(studentClassID).getSinhVien().add(university.getStudentList().get(i));
                    // university.getStudentList().add(i, e);

                }
            }

            AdminView.jTableSinhVien.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien", "mssv", "fullName", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "bangTN"}));
            dao.fillStudentJtable(AdminView.jTableSinhVien, "");
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        //        // TODO add your handling code here:
        DAO dao = new DAO(university);

        //this.dispose();
        if (jTextField_hovaten.getText().equals("") || jTextField_username.getText().equals("") || jTextField_mssv.getText().equals("")
                || jTextField_manganhhoc.getText().equals("") || jTextField_machuongtrinhhoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No selected student");
        } else {
            String studentClassID = jTextField_malop.getText();
            String mssv = jTextField_mssv.getText();
            dao.insertDeleteUpdateStudent('d', null, null, mssv, null, null, null, null, null, null, null, null);
            dao.updateSiSoLopSinhVien('d', studentClassID, university.findStudentClass(studentClassID).getSinhVien().size());
            //AdminView.jTable1.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien", "mssv", "fullName", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "bangTN"}));
            //university.getDao().fillStudentJtable(AdminViewDuc.jTable1, "");
            //university.getStudentList().iterator()
            //
            //university.findStudent(mssv).getBangDiem().clear();

            //university.findStudent(mssv).getHocKySinhVien().clear();
            university.findStudentClass(jTextField_malop.getText()).getSinhVien().remove(university.findStudent(mssv));
            university.getStudentList().remove(university.findStudent(mssv));

            //this.displaySinhVien();
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jTabbedPane3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane3AncestorAdded

    private void jTextFieldCourseID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourseID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourseID2ActionPerformed

    private void jButtonSeeOpeningCourseClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeOpeningCourseClassesActionPerformed
        // TODO add your handling code here:
        //xem cac lop dang mo cua 1 hoc phan thuoc 1 hoc ky
        String maHocKyHeThong = jComboBoxSystemSemeserID3.getSelectedItem().toString();
        String maHocPhan = jTextFieldCourseID2.getText();

        if (maHocKyHeThong.equals("") || maHocPhan.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please input the System semeseter and Course ID!");
        } else {
            displayOpeningCourseClassesBySemesterAndCourse();
        }
    }//GEN-LAST:event_jButtonSeeOpeningCourseClassesActionPerformed

    private void jComboBoxSystemSemeserID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSystemSemeserID3ActionPerformed
        //check check lua chon ma hoc ky cua user
        if (jComboBoxSystemSemeserID3.getSelectedItem().toString().equals("")) {//neu chon item ""
            openingClassesModel.setRowCount(0);
            //do nothing
        } else {//ma hoc ky trong jComboBox luon chinh xac voi sinh vien dang lam viec (tru "")
            displayOpeningCourseClassesBySemester();//hien thi dang ky hoc phan cua sinh vien trong ky hoc tuong ung
        }
    }//GEN-LAST:event_jComboBoxSystemSemeserID3ActionPerformed

    private void jButtonRegisterCourseClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCourseClassActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO(university);

        if (jTextFieldStudentID2.getText().equals("") || jTextFieldCourseClassID.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please input Class ID and Student ID !!");
        } else {
            if (university.findStudent(jTextFieldStudentID2.getText()) == null || !(university.findStudent(jTextFieldStudentID2.getText()) instanceof UnitStudent)) {                JOptionPane.showMessageDialog(rootPane, "Wrong Student ID");
            } else {
                if (university.registerCourseClassForUnitStudent(jTextFieldStudentID2.getText(), jTextFieldCourseClassID.getText(), jComboBoxSystemSemesterID2.getSelectedItem().toString(), dao)) {
                    displayCourseClassRegistration();
                }
            }
        }
    }//GEN-LAST:event_jButtonRegisterCourseClassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRegisterCourse;
    private javax.swing.JButton jButtonRegisterCourseClass;
    private javax.swing.JButton jButtonSeeOpeningCourseClasses;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JComboBox<String> jComboBoxSystemSemeserID3;
    private javax.swing.JComboBox<String> jComboBoxSystemSemesterID1;
    private javax.swing.JComboBox<String> jComboBoxSystemSemesterID2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAdminID;
    private javax.swing.JLabel jLabelSystemSemester;
    private javax.swing.JLabel jLabelToday;
    private javax.swing.JLabel jLabel_find;
    private javax.swing.JLabel jLabel_hesinhvien;
    private javax.swing.JLabel jLabel_hovaten;
    private javax.swing.JLabel jLabel_machuongtrinh;
    private javax.swing.JLabel jLabel_malop;
    private javax.swing.JLabel jLabel_manghanhhoc;
    private javax.swing.JLabel jLabel_mssv;
    private javax.swing.JLabel jLabel_trangthaihoctap;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonnc;
    private javax.swing.JRadioButton jRadioButtontc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTableCourseClassRegistration;
    private javax.swing.JTable jTableCourseRegistration;
    private javax.swing.JTable jTableOpeningCourseClasses;
    public static javax.swing.JTable jTableSinhVien;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldCourseClassID;
    private javax.swing.JTextField jTextFieldCourseID;
    private javax.swing.JTextField jTextFieldCourseID2;
    private javax.swing.JTextField jTextFieldStudentID1;
    private javax.swing.JTextField jTextFieldStudentID2;
    private javax.swing.JTextField jTextField_find;
    private javax.swing.JTextField jTextField_hovaten;
    private javax.swing.JTextField jTextField_machuongtrinhhoc;
    private javax.swing.JTextField jTextField_malop;
    private javax.swing.JTextField jTextField_manganhhoc;
    private javax.swing.JTextField jTextField_mssv;
    private javax.swing.JTextField jTextField_trangthaihoctap;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
