/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;

/**
 *
 * @author haile
 */
public class NewJFrame extends javax.swing.JFrame {

    private Object jButton_add;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel_mssv = new javax.swing.JLabel();
        jLabel_hesinhvien = new javax.swing.JLabel();
        jLabel_machuongtrinh = new javax.swing.JLabel();
        jLabel_malop = new javax.swing.JLabel();
        jLabel_trangthaihoctap = new javax.swing.JLabel();
        jTextFieldStudentFullnameEdit = new javax.swing.JTextField();
        jRadioButtonUnit = new javax.swing.JRadioButton();
        jTextFieldStudentSchoolIDEdit = new javax.swing.JTextField();
        jLabel_manghanhhoc = new javax.swing.JLabel();
        jTextFieldStudentProgramIDEdit = new javax.swing.JTextField();
        jTextFieldStudentStudentClassIDEdit = new javax.swing.JTextField();
        jTextFieldStudentStatusEdit = new javax.swing.JTextField();
        jLabel_find = new javax.swing.JLabel();
        jTextField_find = new javax.swing.JTextField();
        jLabel_trangthaihoctap1 = new javax.swing.JLabel();
        jTextFieldStudentGraduationEdit = new javax.swing.JTextField();
        jLabel_mssv1 = new javax.swing.JLabel();
        jTextFieldStudentStudentIDEdit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_mssv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_mssv.setText("Full name");

        jLabel_hesinhvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_hesinhvien.setText("Type");

        jLabel_machuongtrinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_machuongtrinh.setText("Program");

        jLabel_malop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_malop.setText("Student class");

        jLabel_trangthaihoctap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_trangthaihoctap.setText("Status");

        jTextFieldStudentFullnameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentFullnameEditActionPerformed(evt);
            }
        });

        jRadioButtonUnit.setText("Unit");

        jTextFieldStudentSchoolIDEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentSchoolIDEditActionPerformed(evt);
            }
        });

        jLabel_manghanhhoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_manghanhhoc.setText("School");

        jTextFieldStudentStudentClassIDEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentStudentClassIDEditActionPerformed(evt);
            }
        });

        jTextFieldStudentStatusEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentStatusEditActionPerformed(evt);
            }
        });

        jLabel_find.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-search-25.png"))); // NOI18N
        jLabel_find.setText("Enter value to search student");

        jTextField_find.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_findActionPerformed(evt);
            }
        });
        jTextField_find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_findKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_findKeyReleased(evt);
            }
        });

        jLabel_trangthaihoctap1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_trangthaihoctap1.setText("Graduation");

        jTextFieldStudentGraduationEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentGraduationEditActionPerformed(evt);
            }
        });

        jLabel_mssv1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_mssv1.setText("Student ID");

        jTextFieldStudentStudentIDEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentStudentIDEditActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                        .addComponent(jTextField_find, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_find)
                        .addGap(183, 183, 183))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel_trangthaihoctap)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStudentStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel_machuongtrinh)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStudentProgramIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel_malop)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldStudentStudentClassIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel_manghanhhoc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStudentSchoolIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel_trangthaihoctap1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(jTextFieldStudentGraduationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel_mssv)
                            .addComponent(jLabel_mssv1)
                            .addComponent(jLabel_hesinhvien)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldStudentFullnameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldStudentStudentIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jRadioButtonUnit)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonUnit)
                    .addComponent(jLabel_hesinhvien))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentStudentIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_mssv1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentFullnameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_mssv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentSchoolIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_manghanhhoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentProgramIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_machuongtrinh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentStudentClassIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_malop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_trangthaihoctap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStudentGraduationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_trangthaihoctap1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_find)
                            .addComponent(jButton2)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStudentStudentIDEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentStudentIDEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentStudentIDEditActionPerformed

    private void jTextFieldStudentGraduationEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentGraduationEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentGraduationEditActionPerformed

    private void jTextField_findKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_findKeyReleased

    }//GEN-LAST:event_jTextField_findKeyReleased

    private void jTextField_findKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_findKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_findKeyPressed

    private void jTextField_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_findActionPerformed

    private void jTextFieldStudentStatusEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentStatusEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentStatusEditActionPerformed

    private void jTextFieldStudentStudentClassIDEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentStudentClassIDEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentStudentClassIDEditActionPerformed

    private void jTextFieldStudentSchoolIDEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentSchoolIDEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentSchoolIDEditActionPerformed

    private void jTextFieldStudentFullnameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentFullnameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentFullnameEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel_find;
    private javax.swing.JLabel jLabel_hesinhvien;
    private javax.swing.JLabel jLabel_machuongtrinh;
    private javax.swing.JLabel jLabel_malop;
    private javax.swing.JLabel jLabel_manghanhhoc;
    private javax.swing.JLabel jLabel_mssv;
    private javax.swing.JLabel jLabel_mssv1;
    private javax.swing.JLabel jLabel_trangthaihoctap;
    private javax.swing.JLabel jLabel_trangthaihoctap1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonUnit;
    private javax.swing.JTextField jTextFieldStudentFullnameEdit;
    private javax.swing.JTextField jTextFieldStudentGraduationEdit;
    private javax.swing.JTextField jTextFieldStudentProgramIDEdit;
    private javax.swing.JTextField jTextFieldStudentSchoolIDEdit;
    private javax.swing.JTextField jTextFieldStudentStatusEdit;
    private javax.swing.JTextField jTextFieldStudentStudentClassIDEdit;
    private javax.swing.JTextField jTextFieldStudentStudentIDEdit;
    private javax.swing.JTextField jTextField_find;
    // End of variables declaration//GEN-END:variables
}
