package view;

import control.DAO;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author hai
 */
public class UnitStudentView extends javax.swing.JFrame {

    /*======================= ATTRIBUTEs ==============================*/
    private University university;
    private String mssv;//mssv dang lam viec

    //model de hien thi thong tin
    DefaultTableModel courseRegistrationModel;//hien thi table admin
    DefaultTableModel courseClassRegistrationModel;//hien thi table admin
    DefaultTableModel openingClassesModel;//hien thi table admin

    //nghia
    private DefaultTableModel modelKetQuaHocTap;


    /*======================= CONSTRUCTORs ==============================*/
    /**
     * Creates new form SinhVienTCView
     *
     * @param university
     * @param mssv
     */
    public UnitStudentView(University university, String mssv) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        initComponents();
        this.setLocationRelativeTo(null);

        this.university = university;
        this.mssv = mssv;

        //khoi tao cac table de hien thi du lieu
        courseRegistrationModel = (DefaultTableModel) jTableCourseRegistration.getModel();
        courseClassRegistrationModel = (DefaultTableModel) jTableCourseClassRegistration.getModel();
        openingClassesModel = (DefaultTableModel) jTableOpenningCourseClass.getModel();

        //get cac ma hoc ky he thong cua sinh vien dang lam viec, cho vao list item cua jComboBoxMaHocKyHeThong
        this.getSystemSemesterID();

        //khac
        jLabelStudentID.setText(mssv);
        jLabelToday.setText("Today: " + String.valueOf(university.getToday()));
        jLabelSystemSemester.setText("Semester: " + university.getSystemSemesterList().get(university.getSystemSemesterList().size() - 1).getSystemSemesterID());

        //nghia
        LabelName.setText(university.findStudent(mssv).getHoTen());
        LabelMSSV.setText(mssv);
        LabelTrangThai1.setText(university.findStudent(mssv).getTrangThai());
        LabelNganhHoc.setText(university.findSchool(university.findStudent(mssv).getMaNganhHoc()).getTenNganhHoc());
        LabelChuongTrinhHoc.setText(university.findProgram(university.findStudent(mssv).getMaChuongTrinhHoc()).getTenChuongTrinhHoc());
        LabelLopSV.setText(university.findStudent(mssv).getMaLopSinhVien());

        modelKetQuaHocTap = (DefaultTableModel) jTableKetQuaHocTap.getModel();

        this.displayKetQuaHocTap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSinhVienTCView = new javax.swing.JTabbedPane();
        jPanelHoSoSinhvien = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        LabelName = new javax.swing.JLabel();
        LabelMSSV = new javax.swing.JLabel();
        LabelTrangThai1 = new javax.swing.JLabel();
        LabelLopSV = new javax.swing.JLabel();
        LabelChuongTrinhHoc = new javax.swing.JLabel();
        LabelNganhHoc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKetQuaHocTap = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanelDangKyHocTap = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCourseRegistration = new javax.swing.JTable();
        jButtonDangKyHocPhan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCourseID1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxSystemSemesterID1 = new javax.swing.JComboBox<>();
        jButtonXoaDangKyHocPhan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCourseClassRegistration = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonRegisterCourseClass = new javax.swing.JButton();
        jTextFieldCourseClassID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxSystemSemesterID2 = new javax.swing.JComboBox<>();
        jButtonDeleteCourseClass = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableOpenningCourseClass = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCourseID2 = new javax.swing.JTextField();
        jButtonSeeOpeningCourseClass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSystemSemesterID3 = new javax.swing.JComboBox<>();
        jButtonLogout = new javax.swing.JButton();
        jLabelStudentID = new javax.swing.JLabel();
        jLabelSystemSemester = new javax.swing.JLabel();
        jLabelToday = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unit Student Session");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(231, 208, 208));

        jTabbedPaneSinhVienTCView.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPaneSinhVienTCView.setOpaque(true);

        jPanelHoSoSinhvien.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel8.setToolTipText("");
        jPanel8.setFocusCycleRoot(true);
        jPanel8.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N

        jLabel2.setText("Full name");

        jLabel3.setText("Student ID");

        jLabel5.setText("School");

        jLabel6.setText("Student class");

        jLabel7.setText("Program");

        jButton2.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-password-reset-25.png")); // NOI18N
        jButton2.setText("Change password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LabelName.setText("jLabel11");

        LabelMSSV.setText("jLabel11");

        LabelTrangThai1.setText("jLabel11");

        LabelLopSV.setText("jLabel11");

        LabelChuongTrinhHoc.setText("jLabel11");

        LabelNganhHoc.setText("jLabel11");

        jLabel4.setText("Status");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(65, 65, 65)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTrangThai1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNganhHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(LabelChuongTrinhHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelLopSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jButton2)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(LabelName)
                    .addComponent(LabelNganhHoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(LabelMSSV)
                    .addComponent(LabelChuongTrinhHoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LabelTrangThai1)
                    .addComponent(LabelLopSV)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Information", jPanel8);

        jTableKetQuaHocTap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course name", "Mid-term score", "End-term score", "Course score", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableKetQuaHocTap);
        if (jTableKetQuaHocTap.getColumnModel().getColumnCount() > 0) {
            jTableKetQuaHocTap.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableKetQuaHocTap.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-rating-25.png"))); // NOI18N
        jLabel8.setText("CPA");

        jButton1.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-search-25.png")); // NOI18N
        jButton1.setText("Search course result");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(234, 234, 234))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel8))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Study result", jPanel1);

        javax.swing.GroupLayout jPanelHoSoSinhvienLayout = new javax.swing.GroupLayout(jPanelHoSoSinhvien);
        jPanelHoSoSinhvien.setLayout(jPanelHoSoSinhvienLayout);
        jPanelHoSoSinhvienLayout.setHorizontalGroup(
            jPanelHoSoSinhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanelHoSoSinhvienLayout.setVerticalGroup(
            jPanelHoSoSinhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPaneSinhVienTCView.addTab("PROFILE", jPanelHoSoSinhvien);

        jPanelDangKyHocTap.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jTableCourseRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCourseRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCourseRegistrationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCourseRegistration);

        jButtonDangKyHocPhan.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-add-new-25.png")); // NOI18N
        jButtonDangKyHocPhan.setText("Register course");
        jButtonDangKyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangKyHocPhanActionPerformed(evt);
            }
        });

        jLabel9.setText("Course ID");

        jLabel14.setText("Semester");

        jComboBoxSystemSemesterID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSystemSemesterID1ActionPerformed(evt);
            }
        });

        jButtonXoaDangKyHocPhan.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-clear-symbol-25.png")); // NOI18N
        jButtonXoaDangKyHocPhan.setText("Delete course");
        jButtonXoaDangKyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaDangKyHocPhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSystemSemesterID1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonDangKyHocPhan)
                .addGap(30, 30, 30)
                .addComponent(jButtonXoaDangKyHocPhan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxSystemSemesterID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDangKyHocPhan)
                    .addComponent(jButtonXoaDangKyHocPhan)))
        );

        jTabbedPane2.addTab("Courses", jPanel4);

        jTableCourseClassRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course class ID", "Course ID", "Course name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableCourseClassRegistration);

        jLabel10.setText("Course class");

        jButtonRegisterCourseClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-add-new-25.png"))); // NOI18N
        jButtonRegisterCourseClass.setText("Register class");
        jButtonRegisterCourseClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCourseClassActionPerformed(evt);
            }
        });

        jLabel12.setText("Semester");

        jComboBoxSystemSemesterID2.setSelectedItem(null);
        jComboBoxSystemSemesterID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSystemSemesterID2ActionPerformed(evt);
            }
        });

        jButtonDeleteCourseClass.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-clear-symbol-25.png")); // NOI18N
        jButtonDeleteCourseClass.setText("Delete class");
        jButtonDeleteCourseClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCourseClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxSystemSemesterID2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCourseClassID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegisterCourseClass, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButtonDeleteCourseClass)
                .addGap(110, 110, 110))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCourseClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegisterCourseClass)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxSystemSemesterID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteCourseClass)))
        );

        jTabbedPane2.addTab("Classes", jPanel5);

        jTableOpenningCourseClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course class ID", "Course ID", "Course name", "Capacity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableOpenningCourseClass);

        jLabel11.setText("Course ID");

        jTextFieldCourseID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourseID2ActionPerformed(evt);
            }
        });

        jButtonSeeOpeningCourseClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-view-details-25.png"))); // NOI18N
        jButtonSeeOpeningCourseClass.setText("See opening classes");
        jButtonSeeOpeningCourseClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeOpeningCourseClassActionPerformed(evt);
            }
        });

        jLabel1.setText("Semester");

        jComboBoxSystemSemesterID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSystemSemesterID3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSystemSemesterID3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCourseID2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonSeeOpeningCourseClass)
                .addGap(136, 136, 136))
            .addComponent(jScrollPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonSeeOpeningCourseClass)
                    .addComponent(jTextFieldCourseID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxSystemSemesterID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );

        jTabbedPane2.addTab("Opening classes", jPanel2);

        javax.swing.GroupLayout jPanelDangKyHocTapLayout = new javax.swing.GroupLayout(jPanelDangKyHocTap);
        jPanelDangKyHocTap.setLayout(jPanelDangKyHocTapLayout);
        jPanelDangKyHocTapLayout.setHorizontalGroup(
            jPanelDangKyHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelDangKyHocTapLayout.setVerticalGroup(
            jPanelDangKyHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPaneSinhVienTCView.addTab("STUDY REGISTRATION", jPanelDangKyHocTap);

        jButtonLogout.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-shutdown-25.png")); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelStudentID.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelStudentID.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-graduate-25.png")); // NOI18N
        jLabelStudentID.setText("studentID");

        jLabelSystemSemester.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-calendar-25.png")); // NOI18N
        jLabelSystemSemester.setText("systemSemester");

        jLabelToday.setIcon(new javax.swing.ImageIcon("/home/haile/Downloads/icons8-clock-25.png")); // NOI18N
        jLabelToday.setText("today");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSystemSemester)
                .addGap(81, 81, 81)
                .addComponent(jLabelToday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout)
                .addGap(39, 39, 39))
            .addComponent(jTabbedPaneSinhVienTCView, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jLabelStudentID)
                    .addComponent(jLabelSystemSemester)
                    .addComponent(jLabelToday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneSinhVienTCView))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*======================= DISPLAY CAC BANG/MODEL  ==============================*/
    public void getSystemSemesterID() {//get cac ma hoc ky he thong cua sinh vien dang lam viec
        //cho vao list item cua jComboBoxMaHocKyHeThong
        jComboBoxSystemSemesterID1.removeAllItems();
        jComboBoxSystemSemesterID2.removeAllItems();
        jComboBoxSystemSemesterID3.removeAllItems();
//
//        jComboBoxSystemSemesterID1.addItem("");
//        jComboBoxSystemSemesterID2.addItem("");
//        jComboBoxSystemSemesterID3.addItem("");
        Collections.reverse(university.findStudent(mssv).getHocKySinhVien());//dao thu tu trong hoc ky cua sinh vien !
                                                                            //not hoc ky he thong

        for (StudentSemester a : university.findStudent(mssv).getHocKySinhVien()) {
            jComboBoxSystemSemesterID1.addItem(a.getSystemSemesterID());
            jComboBoxSystemSemesterID2.addItem(a.getSystemSemesterID());
            jComboBoxSystemSemesterID3.addItem(a.getSystemSemesterID());
        }
    }

    public void displayCourseRegistration() {//hien thi cac hoc phan ma 1 sinh vien dang ky // trong 1 ky he thong
        courseRegistrationModel.setRowCount(0);//set model ve 0

        Course h;
        //duyet listMaHocPhanDangKy de hien thi tung hoc phan

        for (String maHocPhan : university.findStudentSemester(mssv, jComboBoxSystemSemesterID1.getSelectedItem().toString()).getMaHocPhanDangKy()) {
            h = university.findCourse(maHocPhan);//tim ra hoc phan tuong ung ma s
            courseRegistrationModel.addRow(new Object[]{
                h.getMaHocPhan(), h.getTenHocPhan()
            });
        }
    }

    public void displayCourseClassRegistration() {//hien thi cac hoc phan ma 1 sinh vien dang ky // trong 1 ky he thong

        courseClassRegistrationModel.setRowCount(0);//set model ve 0

        CourseClass h;
        //duyet listMaHocPhanDangKy de hien thi tung hoc phan

        for (String maLopMo : university.findStudentSemester(mssv, jComboBoxSystemSemesterID2.getSelectedItem().toString()).getMaLopMoDangKy()) {
            h = university.findCourseClass(maLopMo);
            courseClassRegistrationModel.addRow(new Object[]{
                h.getMaLopMo(), h.getMaHocPhan(), university.findCourse(h.getMaHocPhan()).getTenHocPhan()
            });
        }
    }

    public void displayOpeningCourseClassesBySemester() {//hien thi cac hoc phan ma 1 sinh vien dang ky // trong 1 ky he thong

        openingClassesModel.setRowCount(0);//set model ve 0
        SystemSemester hkht = university.findSystemSemester(jComboBoxSystemSemesterID3.getSelectedItem().toString());

        for (CourseClass lopMo : hkht.getLopMo()) {
            if (university.findCourse(lopMo.getMaHocPhan()) instanceof UnitCourse) {//chi show nhung lopMo cua he TC

                if ((university.getToday().after(hkht.getBatDauDangKyLopMo()) && university.getToday().before(hkht.getBatDauHocKy()))) {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Opening for registering"
                    });
                } else {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Closed"
                    });

                }
            }
        }
    }

    public void displayOpeningCourseClassesBySemesterAndCourse() {//hien thi cac hoc phan ma 1 sinh vien dang ky // trong 1 ky he thong

        openingClassesModel.setRowCount(0);//set model ve 0
        SystemSemester hkht = university.findSystemSemester(jComboBoxSystemSemesterID3.getSelectedItem().toString());

        for (CourseClass lopMo : hkht.getLopMo()) {
            if (lopMo.getMaHocPhan().equals(jTextFieldCourseID2.getText())) {//nếu là lớp mở của học phần đang chọn
                if ((university.getToday().after(hkht.getBatDauDangKyLopMo()) && university.getToday().before(hkht.getBatDauHocKy()))) {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Đang mở để đăng ký"
                    });
                } else {
                    openingClassesModel.addRow(new Object[]{
                        lopMo.getMaLopMo(), lopMo.getMaHocPhan(), university.findCourse(lopMo.getMaHocPhan()).getTenHocPhan(),
                        String.valueOf(lopMo.getSinhVien().size() + " / " + lopMo.getSoLuongSinhVienToiDa()),
                        "Đã kết thúc đăng ký"
                    });

                }
            }
        }
    }

    //nghia
    public void displayKetQuaHocTap() {
        for (CourseResult k : university.findStudent(mssv).getBangDiem()) {
            modelKetQuaHocTap.addRow(new Object[]{
                k.getMaHocPhan(), university.findCourse(k.getMaHocPhan()).getTenHocPhan(), k.getDiemGiuaKy(), k.getDiemCuoiKy(),
                k.getDiemHocPhan(), k.getKetQua()
            });
        }

    }

    /*======================= ACTION PERFORMED ==============================*/

    private void jTextFieldCourseID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourseID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourseID2ActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:	
        DAO dao = new DAO(university);

        university.initLoginSession(dao);//yêu cầu university khởi tạo phiên đăng nhập mới
        this.dispose();//xóa phiên làm việc hiện tại

    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jComboBoxSystemSemesterID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSystemSemesterID2ActionPerformed

        //check check lua chon ma hoc ky cua user
        if (jComboBoxSystemSemesterID2.getSelectedItem().toString().equals("")) {//neu chon item ""
            courseRegistrationModel.setRowCount(0);
            //do nothing
        } else {//ma hoc ky trong jComboBox luon chinh xac voi sinh vien dang lam viec (tru "")
            displayCourseClassRegistration();//hien thi dang ky hoc phan cua sinh vien trong ky hoc tuong ung
        }
    }//GEN-LAST:event_jComboBoxSystemSemesterID2ActionPerformed

    private void jButtonDangKyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangKyHocPhanActionPerformed
        DAO dao = new DAO(university);
        if (university.registerCourseForUnitStudent(mssv, jTextFieldCourseID1.getText(), jComboBoxSystemSemesterID1.getSelectedItem().toString(), dao)) {
            displayCourseRegistration();

        }
    }//GEN-LAST:event_jButtonDangKyHocPhanActionPerformed

    private void jComboBoxSystemSemesterID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSystemSemesterID1ActionPerformed

        //check check lua chon ma hoc ky cua user
        if (jComboBoxSystemSemesterID1.getSelectedItem().toString().equals("")) {//neu chon item ""
            courseRegistrationModel.setRowCount(0);
            //do nothing
        } else {//ma hoc ky trong jComboBox luon chinh xac voi sinh vien dang lam viec (tru "")
            displayCourseRegistration();//hien thi dang ky hoc phan cua sinh vien trong ky hoc tuong ung
        }
    }//GEN-LAST:event_jComboBoxSystemSemesterID1ActionPerformed

    private void jButtonRegisterCourseClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCourseClassActionPerformed
        DAO dao = new DAO(university);

        if (university.registerCourseClassForUnitStudent(mssv, jTextFieldCourseClassID.getText(), jComboBoxSystemSemesterID2.getSelectedItem().toString(), dao)) {
            displayCourseClassRegistration();
        }
    }//GEN-LAST:event_jButtonRegisterCourseClassActionPerformed

    private void jButtonSeeOpeningCourseClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeOpeningCourseClassActionPerformed
        // TODO add your handling code here:
        //xem cac lop dang mo cua 1 hoc phan thuoc 1 hoc ky
        String maHocKyHeThong = jComboBoxSystemSemesterID3.getSelectedItem().toString();
        String maHocPhan = jTextFieldCourseID2.getText();

        if (maHocKyHeThong.equals("") || maHocPhan.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please input Semester and Course!");
        } else {
            displayOpeningCourseClassesBySemesterAndCourse();
        }
    }//GEN-LAST:event_jButtonSeeOpeningCourseClassActionPerformed

    private void jComboBoxSystemSemesterID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSystemSemesterID3ActionPerformed
        //check check lua chon ma hoc ky cua user
        if (jComboBoxSystemSemesterID3.getSelectedItem().toString().equals("")) {//neu chon item ""
            openingClassesModel.setRowCount(0);
            //do nothing
        } else {//ma hoc ky trong jComboBox luon chinh xac voi sinh vien dang lam viec (tru "")
            displayOpeningCourseClassesBySemester();//hien thi dang ky hoc phan cua sinh vien trong ky hoc tuong ung
        }
    }//GEN-LAST:event_jComboBoxSystemSemesterID3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        university.initPassSession(mssv);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableCourseRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCourseRegistrationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCourseRegistrationMouseClicked

    private void jButtonXoaDangKyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaDangKyHocPhanActionPerformed
        //neu ko co row nao duoc chon => getSelectedRow = -1
        DAO dao = new DAO(university);

        int selectedRow = jTableCourseRegistration.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select course that you want to delete!");
        } else {
            if (university.delelteCourseRegistrationOfUnitStudent(mssv,
                    jTableCourseRegistration.getValueAt(selectedRow, 0).toString(), jComboBoxSystemSemesterID1.getSelectedItem().toString(), dao)) {
                displayCourseRegistration();
            }
        }
    }//GEN-LAST:event_jButtonXoaDangKyHocPhanActionPerformed

    private void jButtonDeleteCourseClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCourseClassActionPerformed
        //neu ko co row nao duoc chon => getSelectedRow = -1
        DAO dao = new DAO(university);

        int selectedRow = jTableCourseClassRegistration.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select course class that you want to delete!");
        } else {
            if (university.deleteCourseClassRegistrationOfUnitStudent(mssv,
                    jTableCourseClassRegistration.getValueAt(selectedRow, 0).toString(), jComboBoxSystemSemesterID2.getSelectedItem().toString(), dao)) {
                displayCourseClassRegistration();
            }
        }
    }//GEN-LAST:event_jButtonDeleteCourseClassActionPerformed

    /*======================= Các thuộc tính được khởi tạo bằng kéo thả ==========================================*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelChuongTrinhHoc;
    private javax.swing.JLabel LabelLopSV;
    private javax.swing.JLabel LabelMSSV;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelNganhHoc;
    private javax.swing.JLabel LabelTrangThai1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDangKyHocPhan;
    private javax.swing.JButton jButtonDeleteCourseClass;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRegisterCourseClass;
    private javax.swing.JButton jButtonSeeOpeningCourseClass;
    private javax.swing.JButton jButtonXoaDangKyHocPhan;
    private javax.swing.JComboBox<String> jComboBoxSystemSemesterID1;
    private javax.swing.JComboBox<String> jComboBoxSystemSemesterID2;
    private javax.swing.JComboBox<String> jComboBoxSystemSemesterID3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelStudentID;
    private javax.swing.JLabel jLabelSystemSemester;
    private javax.swing.JLabel jLabelToday;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelDangKyHocTap;
    private javax.swing.JPanel jPanelHoSoSinhvien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPaneSinhVienTCView;
    private javax.swing.JTable jTableCourseClassRegistration;
    private javax.swing.JTable jTableCourseRegistration;
    private javax.swing.JTable jTableKetQuaHocTap;
    private javax.swing.JTable jTableOpenningCourseClass;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCourseClassID;
    private javax.swing.JTextField jTextFieldCourseID1;
    private javax.swing.JTextField jTextFieldCourseID2;
    // End of variables declaration//GEN-END:variables
}
